name: fair-software

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  selftest:
    name: "selftest"
    runs-on: ubuntu-latest
    steps:

      - name: Check out a copy of the repository
        uses: actions/checkout@v3

      - uses: ./
        name: Measure compliance with fair-software.eu recommendations
        env:
          PYCHARM_HOSTED: "Trick colorama into displaying colored output"
        with:
          MY_REPO_URL: "https://github.com/${{ github.repository }}"
